### ISSUE TITLE
Bolt 3.3.1 route not found

### ISSUE THREAD

**Issue by simonmnt** [graham73may/bolt-taxonomy-editor#5] opened 2017-07-31 09:46 UTC
I updated bolt, and the routing not match with the new version.

> Uncaught Exception: NotFoundHttpException .
        NotFoundHttpException in RouterListener.php line 176: 
         No route found for "GET /bolt/extensions/taxonomyeditor"

**Comment by graham73may** [comment] 2017-08-02 18:35
Closing as duplicate of #2

Will get this resolved ASAP. Should be pretty quick fix, the extensions URL changed from 3.2 to 3.3 in Bolt...

**Closed as completed by graham73may** 2017-08-02 18:35 UTC

**Comment by graham73may** [comment] 2017-08-02 19:11
@simonmnt 3.3 support added. Please update to 0.3.1

**Comment by simonmnt** [comment] 2017-08-03 07:50
I didn't see the issues, sorry. Thanks for the update.
